version: 1.0.{build}
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    nuget restore FreecamV.sln
build:
  verbosity: minimal
after_build:
- cmd: >-
    7z a FreecamV.zip %APPVEYOR_BUILD_FOLDER%\ImprovedInGameScreenshot\bin\Release\*

    appveyor PushArtifact FreecamV.zip